---
title: "BKN 599 Lecture 1 Notebook- dplyr"
output: html_notebook
---

# Clearing environment, code, closing plots
```{r}
rm(list = ls());
cat("\014")  
graphics.off() 
```

# Loading libraries and dataframes
```{r}
# install.packages("dplyr")
# install.packages("ggplot2")
library(dplyr)
library(ggplot2)

# Loading dataframe
load(file= "vaf_all_data.rda")

df= PC_data_allgroups_uncorrected_difficulty #Simplifying name
df= df[complete.cases(df$NoPeaks_mean), ] # removing rows with NA values

df_stroke = df[df$Group_no==3,] #  Sub setting stroke patients
df_stroke2 = df_stroke[df_stroke$Subject_no<=10,] # Subsetting df for better visualization
df_stroke2= df_stroke2[complete.cases(df_stroke2$NoPeaks_mean), ] # removing rows with NA values

df_healthy = df[df$Group_no==1,] # Sub setting healthy participants
```

# Plots
```{r}
ggplot(df_stroke, aes(NoPeaks_mean))+geom_histogram()
ggplot(df_stroke, aes(NoPeaks_mean))+geom_boxplot()
ggplot(df_stroke, aes(Session_no, NoPeaks_mean))+geom_point(alpha = 0.3)
# Facet_wrap
ggplot(df_stroke2, aes(Session_no, NoPeaks_mean))+geom_point()+facet_wrap(~Subject_no)

# Making plots pretty and setting scales = "free"
ggplot(df_stroke2, aes(Session_no, NoPeaks_mean))+geom_point()+facet_wrap(~Subject_no,scales = "free")+
xlab("Session number")+ ylab("Average number of velocity peaks")+
  theme(
  plot.title = element_text(size=22),
    axis.title.x = element_text(size = 15, angle = 0),
    axis.title.y = element_text(size = 15, angle = 90),
    axis.line = element_line(colour = "black"),
    strip.background = element_blank(),
  panel.background = element_blank())

# Line plots
ggplot(df_stroke2, aes(Session_no, NoPeaks_mean))+geom_line()+facet_wrap(~Subject_no,scales = "free")+
xlab("Session number")+ ylab("Average number of velocity peaks")+
  theme(
  plot.title = element_text(size=22),
    axis.title.x = element_text(size = 15, angle = 0),
    axis.title.y = element_text(size = 15, angle = 90),
    axis.line = element_line(colour = "black"),
    strip.background = element_blank(),
  panel.background = element_blank())

# Observing other variables-
ggplot(df_stroke2, aes(Session_no, NoPeaks_mean, col =Difficulty_level ))+geom_point()+facet_wrap(~Subject_no,scales = "free")+
xlab("Session number")+ ylab("Average number of velocity peaks")+
  theme(
  plot.title = element_text(size=22),
    axis.title.x = element_text(size = 15, angle = 0),
    axis.title.y = element_text(size = 15, angle = 90),
    axis.line = element_line(colour = "black"),
    strip.background = element_blank(),
  panel.background = element_blank())
```



# Basic data-slicing
```{r}
df1 = df[1:100, 1:10]
df2 = df[1:100 ,c("Group_no", "Session_no")]
```


# Dplyr
```{r}
summaries = summarise( df, no_peaks_mean = mean(NoPeaks_mean), no_peaks_median = median(NoPeaks_mean))
# Rewriting using pipes
summaries2 = df %>% summarise( no_peaks_mean = mean(NoPeaks_mean), no_peaks_median = median(NoPeaks_mean))

# Gropby- useful for finding summary properties of groups
group_summaries = df%>% group_by(Group_no) %>% summarise( no_peaks_mean = mean(NoPeaks_mean), no_peaks_median = median(NoPeaks_mean))

# Creating new variables based on other variables
df$new_performance_measure = df$VAF + df$session_accuracy + df$NoPeaks_mean
df = df%>% mutate(new_performance_measure= VAF + session_accuracy + NoPeaks_mean )

# Subsetting rows of dataframe
# Filtering rows
df_smooth = df %>% filter(NoPeaks_mean < 2)
# Remove duplicate rows.

df = distinct(df)
# Randomly select fraction of rows. 
df_sample = df %>% sample_frac(0.5, replace = FALSE) 
df_samplen = df %>% sample_n(100, replace = FALSE) 

# Merging dataframes using sample data frames
df_left = data.frame(subject = c("A","B","C"), var1 = c(1,2,3))
df_right = data.frame(subject = c("A","B","D"), var2 = c(TRUE,TRUE,FALSE))

left_join(df_left,df_right)
right_join(df_left,df_right)
inner_join(df_left,df_right)
full_join(df_left,df_right)

# rename() changes the names of individual variables using new_name = old_name syntax; rename_with() renames columns using a function.
df_left = df_left%>% rename(variable_1 = var1)

# mutate and why it's needed
load("exoskeleton_angles.rda")

# bad way to do it
ggplot(joint_angles)+geom_line(aes(session_time, shoulder_horizontal_angle), col = "blue") + geom_line(aes(session_time, shoulder_elevation_angle), col = "red")

# better way- convert to long format with mutate
angles_melt = joint_angles[, 1:7] %>% melt( id.vars= "session_time")

# Then plot
ggplot(angles_melt,aes(session_time, value, col = variable))+geom_point(size =0.2)
t
```

